"""init

Revision ID: 123d2b4cb73d
Revises:
Create Date: 2026-09-28 20:34:00.997990

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

ENUM_TYPES = ("title_type", "title_category", "title_status", "library_status", "visibility")

# activity_events партиционирована по месяцам. Функция создаёт партицию на месяц,
# если её ещё нет; cron вызывает её раз в неделю на пару месяцев вперёд.
CREATE_PARTITION_FUNCTION = """
create or replace function ensure_activity_events_partition(month date)
returns void language plpgsql as $$
declare
    start_at date := date_trunc('month', month);
    end_at   date := start_at + interval '1 month';
    name     text := format('activity_events_y%sm%s',
                            to_char(start_at, 'YYYY'), to_char(start_at, 'MM'));
begin
    execute format(
        'create table if not exists %I partition of activity_events '
        'for values from (%L) to (%L)',
        name, start_at, end_at
    );
end;
$$;
"""

revision: str = "123d2b4cb73d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("create extension if not exists citext")
    op.execute("create extension if not exists pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titles",
        sa.Column("type", postgresql.ENUM("movie", "show", name="title_type"), nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM("film", "series", "anime", name="title_category"),
            nullable=False,
        ),
        sa.Column("title_ru", sa.Text(), nullable=False),
        sa.Column("title_orig", sa.Text(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=True),
        sa.Column("year", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "announced", "ongoing", "ended", "released", "canceled", name="title_status"
            ),
            server_default="released",
            nullable=False,
        ),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("runtime_min", sa.SmallInteger(), nullable=True),
        sa.Column("poster_path", sa.Text(), nullable=True),
        sa.Column("backdrop_path", sa.Text(), nullable=True),
        sa.Column("genres", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("countries", postgresql.ARRAY(sa.Text()), server_default="{}", nullable=False),
        sa.Column("episodes_total", sa.SmallInteger(), nullable=True),
        sa.Column("ext_rating", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("popularity", sa.Double(), server_default="0", nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('russian', coalesce(title_ru, '')), 'A') || setweight(to_tsvector('simple', coalesce(title_orig, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_titles")),
        sa.UniqueConstraint("slug", name=op.f("uq_titles_slug")),
    )
    op.create_index(
        "ix_titles_ongoing",
        "titles",
        ["status"],
        unique=False,
        postgresql_where=sa.text("status = 'ongoing'"),
    )
    op.create_index(
        "ix_titles_popularity", "titles", [sa.literal_column("popularity desc"), "id"], unique=False
    )
    op.create_index(
        "ix_titles_search", "titles", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_titles_trgm_orig",
        "titles",
        ["title_orig"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_orig": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_titles_trgm_ru",
        "titles",
        ["title_ru"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title_ru": "gin_trgm_ops"},
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("username", postgresql.CITEXT(), nullable=True),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column("locale", sa.Text(), server_default="ru", nullable=False),
        sa.Column("timezone", sa.Text(), server_default="Europe/Moscow", nullable=False),
        sa.Column(
            "profile_visibility",
            postgresql.ENUM("public", "followers", "private", name="visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column("is_pro", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "activity_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=True),
        sa.Column("subject_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("spoiler_rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "visibility",
            postgresql.ENUM("public", "followers", "private", name="visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_activity_events_actor_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_activity_events_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "created_at", name=op.f("pk_activity_events")),
        postgresql_partition_by="RANGE (created_at)",
    )
    op.create_index(
        "ix_activity_events_actor",
        "activity_events",
        ["actor_id", sa.literal_column("created_at desc")],
        unique=False,
        postgresql_where=sa.text("hidden_at is null"),
    )
    op.create_table(
        "collections",
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "visibility",
            postgresql.ENUM("public", "followers", "private", name="visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column("items_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_collections_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
    )
    op.create_index(
        "ix_collections_owner",
        "collections",
        ["owner_id", sa.literal_column("updated_at desc")],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("title_id", sa.BigInteger(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("spoiler_rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["comments.id"],
            name=op.f("fk_comments_parent_id_comments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_comments_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_comments_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index(
        "ix_comments_subject",
        "comments",
        ["subject_type", "subject_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at is null"),
    )
    op.create_table(
        "episodes",
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column("season", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("air_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("runtime_min", sa.SmallInteger(), nullable=True),
        sa.Column(
            "rank",
            sa.Integer(),
            sa.Computed("season::int * 100000 + number::int", persisted=True),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_episodes_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
        sa.UniqueConstraint(
            "title_id", "season", "number", name=op.f("uq_episodes_title_id_season_number")
        ),
    )
    op.create_index(
        "ix_episodes_air_date",
        "episodes",
        ["air_date"],
        unique=False,
        postgresql_where=sa.text("air_date is not null"),
    )
    op.create_index("ix_episodes_title_rank", "episodes", ["title_id", "rank"], unique=False)
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.BigInteger(), nullable=False),
        sa.Column("followee_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("follower_id <> followee_id", name=op.f("ck_follows_not_self")),
        sa.ForeignKeyConstraint(
            ["followee_id"],
            ["users.id"],
            name=op.f("fk_follows_followee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["users.id"],
            name=op.f("fk_follows_follower_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("follower_id", "followee_id", name=op.f("pk_follows")),
    )
    op.create_index("ix_follows_followee", "follows", ["followee_id"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("file_key", sa.Text(), nullable=True),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_import_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dedup_key", sa.Text(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_attempts", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("dedup_key", name=op.f("uq_notifications_dedup_key")),
    )
    op.create_index(
        "ix_notifications_due",
        "notifications",
        ["scheduled_at"],
        unique=False,
        postgresql_where=sa.text("sent_at is null"),
    )
    op.create_table(
        "provider_accounts",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("access_token", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token", sa.LargeBinary(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_provider_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "provider", name=op.f("pk_provider_accounts")),
        sa.UniqueConstraint(
            "provider", "external_id", name=op.f("uq_provider_accounts_provider_external_id")
        ),
    )
    op.create_table(
        "reactions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_type", sa.Text(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), server_default="like", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reactions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "subject_type", "subject_id", "kind", name=op.f("pk_reactions")
        ),
    )
    op.create_index(
        "ix_reactions_subject", "reactions", ["subject_type", "subject_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        "ix_refresh_tokens_active_user_id",
        "refresh_tokens",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at is null"),
    )
    op.create_table(
        "reviews",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("spoiler_rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "visibility",
            postgresql.ENUM("public", "followers", "private", name="visibility"),
            server_default="public",
            nullable=False,
        ),
        sa.Column("likes_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comments_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating between 1 and 10", name=op.f("ck_reviews_rating_range")),
        sa.ForeignKeyConstraint(
            ["title_id"], ["titles.id"], name=op.f("fk_reviews_title_id_titles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_reviews_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    op.create_index(
        "ix_reviews_title",
        "reviews",
        ["title_id", sa.literal_column("created_at desc")],
        unique=False,
        postgresql_where=sa.text("deleted_at is null"),
    )
    op.create_index(
        "uq_reviews_one_per_title",
        "reviews",
        ["user_id", "title_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at is null"),
    )
    op.create_table(
        "title_external_ids",
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_title_external_ids_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("provider", "external_id", name=op.f("pk_title_external_ids")),
    )
    op.create_index(
        op.f("ix_title_external_ids_title_id"), "title_external_ids", ["title_id"], unique=False
    )
    op.create_table(
        "user_titles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "planned", "watching", "completed", "on_hold", "dropped", name="library_status"
            ),
            nullable=False,
        ),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("progress_rank", sa.Integer(), server_default="0", nullable=False),
        sa.Column("episodes_watched", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("rewatch_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rating between 1 and 10", name=op.f("ck_user_titles_rating_range")),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_user_titles_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_titles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "title_id", name=op.f("pk_user_titles")),
    )
    op.create_index(
        "ix_user_titles_rated",
        "user_titles",
        ["title_id", "rating"],
        unique=False,
        postgresql_where=sa.text("rating is not null"),
    )
    op.create_index(
        "ix_user_titles_status",
        "user_titles",
        ["user_id", "status", sa.literal_column("updated_at desc")],
        unique=False,
    )
    op.create_index(
        "ix_user_titles_watching",
        "user_titles",
        ["title_id"],
        unique=False,
        postgresql_where=sa.text("status in ('watching', 'planned')"),
    )
    op.create_table(
        "collection_items",
        sa.Column("collection_id", sa.BigInteger(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_items_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_collection_items_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("collection_id", "title_id", name=op.f("pk_collection_items")),
    )
    op.create_index(
        "ix_collection_items_position",
        "collection_items",
        ["collection_id", "position"],
        unique=False,
    )
    op.create_table(
        "import_items",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=True),
        sa.Column("match_score", sa.Double(), nullable=True),
        sa.Column("match_state", sa.Text(), nullable=False),
        sa.Column("applied", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["import_jobs.id"],
            name=op.f("fk_import_items_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_import_items_title_id_titles"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_items")),
    )
    op.create_index(
        "ix_import_items_job_state", "import_items", ["job_id", "match_state"], unique=False
    )
    op.create_table(
        "user_episodes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("episode_id", sa.BigInteger(), nullable=False),
        sa.Column("title_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "watched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
            name=op.f("fk_user_episodes_episode_id_episodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
            name=op.f("fk_user_episodes_title_id_titles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_episodes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "episode_id", name=op.f("pk_user_episodes")),
    )
    op.create_index(
        "ix_user_episodes_user_title", "user_episodes", ["user_id", "title_id"], unique=False
    )
    op.create_index(
        "ix_user_episodes_user_watched",
        "user_episodes",
        ["user_id", sa.literal_column("watched_at desc")],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute(CREATE_PARTITION_FUNCTION)
    # текущий месяц и два следующих, дальше досоздаёт cron
    for offset in range(3):
        op.execute(
            "select ensure_activity_events_partition("
            f"(date_trunc('month', now()) + interval '{offset} month')::date)"
        )


def downgrade() -> None:
    op.execute("drop function if exists ensure_activity_events_partition(date)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_episodes_user_watched", table_name="user_episodes")
    op.drop_index("ix_user_episodes_user_title", table_name="user_episodes")
    op.drop_table("user_episodes")
    op.drop_index("ix_import_items_job_state", table_name="import_items")
    op.drop_table("import_items")
    op.drop_index("ix_collection_items_position", table_name="collection_items")
    op.drop_table("collection_items")
    op.drop_index(
        "ix_user_titles_watching",
        table_name="user_titles",
        postgresql_where=sa.text("status in ('watching', 'planned')"),
    )
    op.drop_index("ix_user_titles_status", table_name="user_titles")
    op.drop_index(
        "ix_user_titles_rated",
        table_name="user_titles",
        postgresql_where=sa.text("rating is not null"),
    )
    op.drop_table("user_titles")
    op.drop_index(op.f("ix_title_external_ids_title_id"), table_name="title_external_ids")
    op.drop_table("title_external_ids")
    op.drop_index(
        "uq_reviews_one_per_title",
        table_name="reviews",
        postgresql_where=sa.text("deleted_at is null"),
    )
    op.drop_index(
        "ix_reviews_title", table_name="reviews", postgresql_where=sa.text("deleted_at is null")
    )
    op.drop_table("reviews")
    op.drop_index(
        "ix_refresh_tokens_active_user_id",
        table_name="refresh_tokens",
        postgresql_where=sa.text("revoked_at is null"),
    )
    op.drop_table("refresh_tokens")
    op.drop_index("ix_reactions_subject", table_name="reactions")
    op.drop_table("reactions")
    op.drop_table("provider_accounts")
    op.drop_index(
        "ix_notifications_due",
        table_name="notifications",
        postgresql_where=sa.text("sent_at is null"),
    )
    op.drop_table("notifications")
    op.drop_table("import_jobs")
    op.drop_index("ix_follows_followee", table_name="follows")
    op.drop_table("follows")
    op.drop_index("ix_episodes_title_rank", table_name="episodes")
    op.drop_index(
        "ix_episodes_air_date",
        table_name="episodes",
        postgresql_where=sa.text("air_date is not null"),
    )
    op.drop_table("episodes")
    op.drop_index(
        "ix_comments_subject", table_name="comments", postgresql_where=sa.text("deleted_at is null")
    )
    op.drop_table("comments")
    op.drop_index("ix_collections_owner", table_name="collections")
    op.drop_table("collections")
    op.drop_index(
        "ix_activity_events_actor",
        table_name="activity_events",
        postgresql_where=sa.text("hidden_at is null"),
    )
    op.drop_table("activity_events")
    op.drop_table("users")
    op.drop_index(
        "ix_titles_trgm_ru",
        table_name="titles",
        postgresql_using="gin",
        postgresql_ops={"title_ru": "gin_trgm_ops"},
    )
    op.drop_index(
        "ix_titles_trgm_orig",
        table_name="titles",
        postgresql_using="gin",
        postgresql_ops={"title_orig": "gin_trgm_ops"},
    )
    op.drop_index("ix_titles_search", table_name="titles", postgresql_using="gin")
    op.drop_index("ix_titles_popularity", table_name="titles")
    op.drop_index(
        "ix_titles_ongoing", table_name="titles", postgresql_where=sa.text("status = 'ongoing'")
    )
    op.drop_table("titles")
    # ### end Alembic commands ###

    for enum_type in ENUM_TYPES:
        op.execute(f"drop type if exists {enum_type}")
